"""
Module for converting musical notes into bass guitar tablature.
Applies fretboard optimization logic and formats the output into readable ASCII text 
with rhythmic spacing.
"""
import librosa

# Standard EADG Bass Tuning in MIDI values
# The bottom line represents the E string.
# The top line represents the G string.
TUNING_MIDI = {
    'G': 43,
    'D': 38,
    'A': 33,
    'E': 28
}

MAX_FRET = 22


def map_notes_to_frets(notes: list[dict]) -> list[dict]:
    """
    Takes a sequence of notes and determines the optimal string and fret 
    for each, minimizing hand movement across the fretboard.
    """
    fretted_notes = []
    prev_fret = 3

    for note_data in notes:
        target_midi = librosa.note_to_midi(note_data['note'])
        possible_positions = []

        for string_name, string_midi in TUNING_MIDI.items():
            fret_needed = target_midi - string_midi
            if 0 <= fret_needed <= MAX_FRET:
                possible_positions.append({
                    'string': string_name,
                    'fret': fret_needed
                })

        best_position = None
        lowest_cost = float('inf')

        if not possible_positions:
            best_position = {'string': 'E', 'fret': int(target_midi - 28)}
        else:
            for pos in possible_positions:
                if pos['fret'] == 0:
                    cost = 0
                else:
                    cost = abs(pos['fret'] - prev_fret)

                if cost > 8:
                    cost += 50

                if cost < lowest_cost:
                    lowest_cost = cost
                    best_position = pos

        note_data['string'] = best_position['string']
        note_data['fret'] = best_position['fret']
        fretted_notes.append(note_data)

        if best_position['fret'] != 0:
            prev_fret = best_position['fret']

    return fretted_notes


def generate_tab_text(fretted_notes: list[dict]) -> str:
    """
    Formats a sequence of fretted notes into a standard text-based bass tab.
    Implements rhythmic spacing based on note duration and start times.
    """
    if not fretted_notes:
        return "No notes detected to tab!"

    final_tab_string = "🎸 BASS TAB GENERATED BY AI PIPELINE 🎸\n"
    final_tab_string += "\n"  # Blank line after header

    # We define our "grid resolution".
    # 0.1 seconds equals one dash '-' in the tab.
    # This allows the player to visually read the rhythm.
    TIME_PER_DASH = 0.1

    # A standard measure (bar) in 4/4 time at 120bpm is 2.0 seconds long.
    # We will draw a vertical bar line '|' every 2.0 seconds.
    BAR_LENGTH_SECONDS = 2.0

    # We will chunk the output so it doesn't scroll infinitely right.
    # Let's put 4 bars per line block.
    BLOCK_LENGTH_SECONDS = BAR_LENGTH_SECONDS * 4

    # Find the total length of the song based on the last note
    last_note = fretted_notes[-1]
    total_duration = last_note['start_time'] + last_note['duration']

    current_time = 0.0
    note_index = 0

    # Loop through the song, chunking it into blocks of 8 seconds
    while current_time < total_duration:

        block_end_time = current_time + BLOCK_LENGTH_SECONDS

        # Initialize empty strings for this block
        lines = {
            'G': "G |",
            'D': "D |",
            'A': "A |",
            'E': "E |"
        }

        # Walk through this specific 8-second block in 0.1s steps
        step_time = current_time
        while step_time < block_end_time:

            # Are we at a measure boundary? Draw a bar line!
            # Bars help you figure out the structure and rhythm of a song.
            if round(step_time % BAR_LENGTH_SECONDS, 2) == 0.0 and step_time != current_time:
                for s in lines:
                    lines[s] += "|"

            # Check if our current note should be played at this exact step_time
            if note_index < len(fretted_notes):
                current_note = fretted_notes[note_index]

                # If the note starts exactly now (or we just passed its start time)
                if current_note['start_time'] <= step_time < (current_note['start_time'] + TIME_PER_DASH):
                    played_string = current_note['string']
                    fret = str(current_note['fret'])

                    # Format the fret number to take up consistent space
                    fret_str = fret if len(fret) == 2 else f"{fret}-"

                    for s in lines.keys():
                        if s == played_string:
                            lines[s] += fret_str
                        else:
                            lines[s] += "--"

                    # Move to the next note, but only step time forward by 0.1s
                    note_index += 1
                    step_time += TIME_PER_DASH * 2  # Skip extra space since we printed 2 chars
                    continue

            # If no note is starting right now, just print an empty dash for rhythm spacing
            for s in lines.keys():
                lines[s] += "-"
            step_time += TIME_PER_DASH

        # Add the completed block to the final text document
        final_tab_string += lines['G'] + "\n"
        final_tab_string += lines['D'] + "\n"
        final_tab_string += lines['A'] + "\n"
        final_tab_string += lines['E'] + "\n"
        final_tab_string += "\n"  # Blank line between blocks

        current_time = block_end_time

    return final_tab_string
